# Generated by Django 4.2.1 on 2023-05-10 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='nivel',
            field=models.PositiveIntegerField(choices=[(1, 1), (3, 3), (5, 5), (8, 8)]),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='prioridade',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3)]),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='situacao',
            field=models.CharField(choices=[('NOVA', 'NOVA'), ('EM ANDAMENTO', 'EM ANDAMENTO'), ('PENDENTE', 'PENDENTE'), ('RESOLVIDA', 'RESOLVIDA'), ('CANCELADA', 'CANCELADA')]),
        ),
    ]
